site_name: BiznetGIO Docs
site_description: BiznetGIO documentation

repo_url: https://github.com/BiznetGIO/biznetgio.github.io/

theme:
    name: 'material'
    favicon: 'img/logo.png'
    logo: 'img/logo.png'
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - Guide:
        - Dockerize Flask App: guide/dockerize-flask.md
        - Deploying App: guide/deploy-app.md
        - Standards: guide/standards.md
        - Contribution Guide: guide/contrib-guide.md
        - Testing Minimalist: guide/test-minimalist.md
        - Common Errors: guide/common-errors.md
        - Project Boilerplates: guide/boilerplates.md
        - RESTKnot:
            - Knot Clash Course: guide/knot-clash-course.md
            - RESTKnot Setup: guide/knot-setups.md
    - About:
        - Contributing: about/contributing.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2019 BiznetGio.

plugins:
    - search
