site_name: BiznetGIO Docs
site_description: BiznetGIO documentation

repo_url: https://github.com/BiznetGIO/biznetgio.github.io/
edit_uri: 'edit/source/docs/'

theme:
    name: 'material'
    favicon: 'img/logo.png'
    logo: 'img/logo_white.png'
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - Engineering:
        - Intro: guide/contrib-intro.md
        - Contribute Guideline: 
            - Guidelines: guide/contrib-guide.md
            - Standards: guide/standards.md
            - Project Boilerplates: guide/boilerplates.md
        - Development Workflow:
            - Prefix: guide/bgn-dev-welcome.md 
            - First Setup: guide/bgn-dev-initiliaze.md
            - Managing Project: guide/bgn-dev-manage-project.md
            - Managing CI/CD: guide/managing-ci-cd.md
            - Deployment: 
                - Container Production Enviroment: guide/container-production-enviroment.md
                - Deployment Staging: guide/deployment-staging.md
                - Deployment Production: guide/deployment-production.md
            - Logs:
                - Testing Minimalist: guide/test-minimalist.md
                - Integrations Test : guide/integrations-test.md
                - Sonarqube Code Analyzer: guide/sonarqube-documentations.md
        - Reporting Workflow:
            - Task Board: guide/task-board.md
            - Report: guide/reporting-workflow.md
            - Logs: guide/logger-dashboard.md
        - Clash Course:
            - Dockerize Flask App: guide/dockerize-flask.md
            - Deploy App on Devbox: guide/deploy-app.md
            - Common Errors: guide/common-errors.md
            - Gunicorn Best Practice: guide/gunicorn.md
            - Git Tips and Tricks: guide/git-tutorial.md
        - Featured Tools:
            - Tunneling Staging Apps: guide/bgn-dev-remote-tunnel.md
            - Proxy: guide/bgn-dev-remote-proxy.md
            - Logging: guide/bgn-dev-remote-logs.md
    - About:
        - Contributing: about/contributing.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - pymdownx.superfences
    - pymdownx.emoji
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2019 BiznetGio.

plugins:
    - search
