name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - source

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        script: pip install -r requirements.txt
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: guide.biznetgio.dev
          CONFIG_FILE: mkdocs.yml
#           EXTRA_PACKAGES: build-base
